---
title: "Mamals...stuff dataset"
output: 
  html_document:
    keep_md: true
---

# "Something about sea animals stuff" Dataset

I am following @rtatman's tutorial on this dataset, just doing it with RMarkdown instead.

# Section 1

```{r housing}
library(tidyverse)
library(data.table)
```

I'll be using `data.table` instead of the normal Tibble, for learning purposes.

```{r}
musselData <- fread("data/histopaths.csv")
```

And get the dimensions
```{r}
dim(musselData)
```

# Section 2 - Piping

```{r}
columnNames <- musselData %>%
  names() %>%
  sort()
head(columnNames)
```


# Section 3

```{r}
musselData %>%
  select(starts_with('cestode')) %>%
  summary()
```

```{r}
musselData %>%
  select(-starts_with('cestode')) %>%
  names() %>%
  sort() %>%
  head(20) 
```

# Section 4

```{r}
musselData %>%
  filter(abnormality > 3)
```

```{r}
musselData %>%
  filter(coastal_ecological_area == 'Lake Michigan')
```

```{r}
plyrWay3 <- musselData %>%
  filter(sex == 'Male' & state_name == 'Mississippi')
tableWay <- musselData[sex == 'Male' & state_name == 'Mississippi']
all.equal(plyrWay3, tableWay)
```

# Section 5

```{r}
musselData %>%
  mutate(large_mussels = (wet_weight > 10)) %>%
  select(large_mussels) %>%
  summary()
```

```{r}
musselData %>%
  mutate(parasites = (wet_weight > .5 & unidentified_organism > 1)) %>%
  select(parasites) %>%
  summary()
```

# Section 6

```{r}
musselData %>%
  arrange(desc(length)) %>%
  select(length) %>%
  head()
```

# Section 7

```{r}
musselData %>%
  summarize(meanLength = mean(length), medianLength = median(length, na.rm = T))
```

# Section 8

```{r}
musselData %>%
  group_by(state_name) %>%
  summarize(meanLength = mean(length), medianLength = median(length, na.rm=T))
```

```{r}
musselData %>%
  group_by(coastal_ecological_area) %>%
  summarize(meanLength = mean(length), medianLength = median(length, na.rm=T))
```
